services:
  # Video Input
  vidin:
    image: us-west1-docker.pkg.dev/plainsightai-prod/oci/video_in:v1.4.18
    environment:
      FILTER_ID: filter_connector_gcs-input
      FILTER_SOURCES: "file:///video.mp4!sync!resize=960x540lin!loop"
      FILTER_OUTPUTS: "tcp://*:6000"
    volumes:
      - ${VIDEO_INPUT}:/video.mp4:ro
    ports:
      - "6000:6000"

  # Frame Deduplication
  frame_dedup:
    image: us-west1-docker.pkg.dev/plainsightai-prod/oci/filter-frame-dedup:v1.0.8
    environment:
      FILTER_ID: frame_dedup
      FILTER_SOURCES: "tcp://vidin:6000"
      FILTER_OUTPUTS: "tcp://*:6001"
      FILTER_HASH_THRESHOLD: "${FILTER_HASH_THRESHOLD:-5}"
      FILTER_MOTION_THRESHOLD: "${FILTER_MOTION_THRESHOLD:-1200}"
      FILTER_MIN_TIME_BETWEEN_FRAMES: "${FILTER_MIN_TIME_BETWEEN_FRAMES:-1.0}"
      FILTER_SSIM_THRESHOLD: "${FILTER_SSIM_THRESHOLD:-0.90}"
      FILTER_OUTPUT_FOLDER: "/app/output"
    volumes:
      - ./output:/app/output
    ports:
      - "6001:6001"

  # Video to GCS Upload
  filter_connector_gcs:
    image: us-west1-docker.pkg.dev/plainsightai-prod/oci/filter-connector-gcs:v1.5.2
    environment:
      FILTER_ID: filter_connector_gcs
      FILTER_SOURCES: "tcp://frame_dedup:6001"
      FILTER_OUTPUTS: ${GCP_STORAGE_URL}
      FILTER_EXIT_AFTER: "${FILTER_EXIT_AFTER:-48:00:00}"
      FILTER_IMAGE_FOLDER: /app/output
      FILTER_MQ_LOG: pretty
      GOOGLE_APPLICATION_CREDENTIALS: "/run/secrets/google"
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
    secrets:
      - google
    volumes:
      - ./output:/app/output

  # Web Visualization
  webvis:
    image: us-west1-docker.pkg.dev/plainsightai-prod/oci/webvis:v1.4.18
    environment:
      FILTER_ID: webvis
      FILTER_SOURCES: "tcp://frame_dedup:6001"
    ports:
      - 8002:8000

# SECRETS:
secrets:
  google:
    file: ${GOOGLE_APPLICATION_CREDENTIALS}