services:
  # Video Input
  vidin:
    image: us-west1-docker.pkg.dev/plainsightai-prod/oci/video_in:v1.4.18
    environment:
      FILTER_ID: vidin
      FILTER_SOURCES: "file:///video.mp4!sync!resize=960x540lin!loop"
      FILTER_OUTPUTS: "tcp://*:6000"
    volumes:
      - ${VIDEO_INPUT}:/video.mp4:ro

  # Video to GCS Upload
  filter_connector_gcs:
    image: us-west1-docker.pkg.dev/plainsightai-prod/oci/filter-connector-gcs:v1.5.2
    environment:
      FILTER_ID: filter_connector_gcs
      FILTER_SOURCES: "tcp://vidin:6000"
      FILTER_OUTPUTS: ${GCP_STORAGE_URL}
      FILTER_EXIT_AFTER: "${FILTER_EXIT_AFTER:-48:00:00}"
      FILTER_IMAGE_FOLDER: /app/output
      FILTER_MQ_LOG: pretty
      GOOGLE_APPLICATION_CREDENTIALS: "/run/secrets/google"
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
    secrets:
      - google
    volumes:
      - ./work:/filter/work:rw

# SECRETS:
secrets:
  google:
    file: ${GOOGLE_APPLICATION_CREDENTIALS}